"""generating missing columns

Revision ID: e5254cea360d
Revises: f562d4b211b7
Create Date: 2022-12-30 13:46:01.353077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5254cea360d'
down_revision = 'f562d4b211b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
